apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  namespace: app
  name: test
spec:
  pipelineRef:
    resolver: cluster
    params:
    - name: kind
      value: pipeline
    - name: namespace
      value: pipelines
    - name: name
      value: simple-echo-pipeline