apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelineruns-rolebinding
  namespace: app
subjects:
- kind: User
  name: user2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tekton-pipelineruns-role
  apiGroup: rbac.authorization.k8s.io
