apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipeline-admin-binding
  namespace: pipelines
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tekton-pipeline-admin
  apiGroup: rbac.authorization.k8s.io
