apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pipelines
  name: tekton-pipeline-admin
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns", "pipelineresources", "tasks", "taskruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
