apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roles
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  source:
    path: ocp/roles
    repoURL: "https://github.com/dbgjerez/tekton-pipelineref.git"
    targetRevision: main
  project: default