apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-msg
  namespace: pipelines
spec:
  workspaces:
  - name: pvc-msg
  steps:
    - name: echo
      image: fedora
      command:
        - cat
      args:
        - msg/README.md
