apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-msg
  namespace: pipelines
spec:
  workspaces:
  - name: pvc-msg
  steps:
    - name: write
      image: fedora
      script: echo "Hello world!" > $(workspaces.pvc-msg.path)/README.md
