apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-msg
  namespace: pipelines
spec:
  steps:
    - name: echo
      image: fedora
      command:
        - echo
      args:
        - 'hello world > msg/README.md'
