apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-echo-pipeline
  namespace: pipelines
spec:
  tasks:
    - name: write
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: write-msg
        - name: namespace
          value: pipelines
    - name: read
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: read-msg
        - name: namespace
          value: pipelines
      runAfter:
        - "write"