apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-echo-pipeline
  namespace: pipelines
spec:
  workspaces:
  - name: pvc-msg
  tasks:
    - name: write
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: write-msg
        - name: namespace
          value: pipelines
      workspaces:
        - name: pvc-msg
          workspace: pvc-msg
    - name: read
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: read-msg
        - name: namespace
          value: pipelines
      workspaces:
        - name: pvc-msg
          workspace: pvc-msg
      runAfter:
        - "write"